name: Build and Deploy Backend & Frontend Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Backend Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest ./backend

    - name: Build Frontend Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest ./frontend

    - name: Push Backend Image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

    - name: Push Frontend Image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker network inspect devops-network >/dev/null 2>&1 || docker network create devops-network
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

          # Stop and remove old containers if exist
          docker stop backend || true
          docker rm backend || true
          docker stop frontend || true
          docker rm frontend || true

          # Pull latest images
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

          # Run backend container
          docker run -d --name backend --network devops-network -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

          # Run frontend container
          docker run -d --name frontend --network devops-network -p 3000:80 ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

